# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://davegeneral.github.io/
date_format: "ordinal"
title: 码尾辫儿
subtitle: "沧桑过往,老码识途"
description: "Will的个人博客"
keywords: 码农, Will, davegeneral, 码尾辫儿
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Will
organization: SDU_IRLab
organization_url: https://davegeneral.github.io/
github_username: DaveGeneral
location: QingDao, China
email: 1903404743@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: DaveGeneral/DaveGeneral.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: DaveGeneral
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: DaveGeneral
    repo: blog-comments
    oauth:
        client_id: 2dee75147428fe382419
        client_secret: 2eb4382e082ffd4024936f46939c226bcbe54a35
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: DaveGeneral
    repo: blog-comments
    clientID: 2dee75147428fe382419
    clientSecret: 2eb4382e082ffd4024936f46939c226bcbe54a35
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
